[package]
name = "gosh-calc"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A calculator for the COSMIC desktop"
repository = "https://github.com/goshitsarch-eng/Gosh-Calc"

[dependencies]
libcosmic = { git = "https://github.com/pop-os/libcosmic.git", rev = "b728852754db54201002b84d9279a207f00de8f2", default-features = false, features = [
    "winit",
    "tokio",
    "a11y",
    "x11",
    "wayland",
    "wgpu",
    "xdg-portal",
] }
serde = { version = "1", features = ["derive"] }
env_logger = "0.11"
log = "0.4"
i18n-embed = { version = "0.16", features = [
    "fluent-system",
    "desktop-requester",
] }
i18n-embed-fl = "0.10"
rust-embed = "8"

[profile.release]
lto = "thin"
opt-level = 3
